%% x-line tracking
xline                  = struct(...
                            'name',     'x_line_tracking',...
                            'type',     'bucket'                    ,...
                            'c_pos',    [0 0 10]                    ,...
                            'c_fun', @(t) [50*sin(1/50*4*t) 0 10],...
                            'varargin', struct(                     ...
                                'v_max',         3,...
                                'v_min',         1.0...
                            )...
                          );
%% Bucket
buck                    = struct(...
                            'name',     'bucket',...
                            'type',     'bucket'                    ,...
                            'c_pos',    [0 0 10]                    ,...
                            'varargin', struct(                     ...
                                'v_max',         3,...
                                'v_min',         0.5...
                            )...
                          );
%% Two point circles
two_point_circ(1)        = struct(...
                            'name', 'two_point_circles',...
                            'type',     'point'                    ,...
                            'c_pos',    [-20 0 10]                    ,...
                            'c_fun', @(t) [-10*cos(1/10*3*t)-10 10*sin(1/10*3*t) 10],...
                            'varargin', struct('v_max', 3)...
                          );
two_point_circ(2)        = struct(...
                            'name', 'two_point_circles',...
                            'type',     'point'                    ,...
                            'c_pos',    [20 0 10]                    ,...
                            'c_fun', @(t) [10*cos(1/10*3*t)+10 10*sin(1/10*3*t) 10],...
                            'varargin', struct('v_max', 3)...
                          );
%% Two bucket circles
two_buck_circ(1)        = struct(...
                            'name', 'two_bucket_circles',...
                            'type',     'bucket'                    ,...
                            'c_pos',    [-20 0 10]                    ,...
                            'c_fun', @(t) [-10*cos(1/10*3*t)-10 10*sin(1/10*3*t) 10],...
                            'varargin', struct(                     ...
                                'v_max',         3,...
                                'v_min',         0.5...
                            )...
                          );
two_buck_circ(2)        = struct(...
                            'name', 'two_bucket_circles',...
                            'type',     'bucket'                    ,...
                            'c_pos',    [20 0 10]                    ,...
                            'c_fun', @(t) [10*cos(1/10*3*t)+10 10*sin(1/10*3*t) 10],...
                            'varargin', struct(                     ...
                                'v_max',         3,...
                                'v_min',         0.5...
                            )...
                          );
%% Two circles
two_circ(1)            = struct(                                   ...
                            'name', 'two_circles',...
                            'type',     'circle'                    ,...
                            'c_pos',    [-8 0 10]                    ,...
                            'varargin', struct(                     ...
                                'radius',           7.5               ,...
                                'v_max',            3    ,...
                                'direction',        1               ,...
                                'bandwidth_gain',   0.01            ,...
                                'spiral_gain',      6               ...
                            )                                       ...
                          );   
two_circ(2)            = struct(                                   ...
                            'name', 'two_circles',...
                            'type',     'circle'                    ,...
                            'c_pos',    [8 0 10]                    ,...
                            'varargin', struct(                     ...
                                'radius',           7.5               ,...
                                'v_max',            3    ,...
                                'direction',        -1              ,...
                                'bandwidth_gain',   0.01            ,...
                                'spiral_gain',      6               ...
                            )                                       ...
                          ); 